export const IMPORT_ANCHOR = `import Phaser from "phaser";`;
export const IMPORT_REPLACEMENT = `import Phaser from "phaser";\nimport { isEnemyMovementBlocked } from "./game/enemyCollision";\nimport { findFirstReachableReroute, getPreviousSafeGridWaypoints, orderExitChoices } from "./game/enemyReroute";`;

export const FIELD_ANCHOR = "  private pathRecalculationVersion = 0;";
export const FIELD_REPLACEMENT = `  private pathRecalculationVersion = 0;\n  private pendingEnemyReroutes = new WeakSet<Enemy>();`;

export const FOLLOW_PATH_ANCHOR = `  private followPath(enemy: Enemy, delta: number, speed: number): void {\n    const target = enemy.path[enemy.pathIndex];\n    if (!target) {\n      this.recalculateEnemyPath(enemy);\n      return;\n    }\n\n    const distance = Phaser.Math.Distance.Between(enemy.body.x, enemy.body.y, target.x, target.y);\n    const step = speed * (delta / 1000);\n    if (distance <= step) {\n      enemy.body.setPosition(target.x, target.y);\n      enemy.pathIndex += 1;\n      return;\n    }\n    enemy.body.x += ((target.x - enemy.body.x) / distance) * step;\n    enemy.body.y += ((target.y - enemy.body.y) / distance) * step;\n  }`;

/** Runtime wiring only: route search itself lives in src/game/enemyReroute.ts. */
export const SAFE_REROUTE_METHOD = `  private rerouteEnemyFromSafeWaypoint(enemy: Enemy): boolean {\n    const halfPlant = PLANT_FRAME_SIZE / 2 - 1;\n    const rightExit = {\n      id: "right" as ExitId,\n      col: TOP_EXIT_COL,\n      row: TOP_EXIT_ROW,\n      x: this.gridToWorldX(TOP_EXIT_COL, TOP_EXIT_ROW),\n      y: this.gridToWorldY(TOP_EXIT_ROW),\n    };\n    const bottomExit = {\n      id: "bottom" as ExitId,\n      col: BOTTOM_EXIT_COL,\n      row: BOTTOM_EXIT_ROW,\n      x: this.gridToWorldX(BOTTOM_EXIT_COL, BOTTOM_EXIT_ROW),\n      y: this.gridToWorldY(BOTTOM_EXIT_ROW),\n    };\n    const exits = orderExitChoices(enemy.exitId, [rightExit, bottomExit]);\n    const safeWaypoints = getPreviousSafeGridWaypoints(\n      enemy.path,\n      enemy.pathIndex,\n      this.towers,\n      {\n        cell: CELL,\n        originX: GRID_X,\n        originY: GRID_Y,\n        columns: GRID_COLS,\n        rows: GRID_ROWS,\n        plantHalfSize: halfPlant,\n      },\n      (col, row) => ({ x: this.gridToWorldX(col, row), y: this.gridToWorldY(row) }),\n    );\n    const plan = findFirstReachableReroute(\n      safeWaypoints,\n      exits,\n      (from, to) => this.calculatePath(from, to),\n    );\n    if (!plan) return false;\n\n    const { waypoint, exit, route } = plan;\n    enemy.body.setPosition(waypoint.x, waypoint.y);\n    enemy.exitId = exit.id;\n    enemy.exitCol = exit.col;\n    enemy.exitRow = exit.row;\n    enemy.exitX = exit.x;\n    enemy.exitY = exit.y;\n    enemy.path = [\n      new Phaser.Math.Vector2(waypoint.x, waypoint.y),\n      ...route.map((point) => new Phaser.Math.Vector2(point.x, point.y)),\n      new Phaser.Math.Vector2(exit.x, exit.y),\n    ];\n    enemy.pathIndex = 1;\n    this.pendingEnemyReroutes.delete(enemy);\n    return true;\n  }`;

/** Movement plus the anti-tunnelling guard. */
export const FOLLOW_PATH_METHOD = `  private followPath(enemy: Enemy, delta: number, speed: number): void {\n    const target = enemy.path[enemy.pathIndex];\n    if (!target) {\n      this.pendingEnemyReroutes.delete(enemy);\n      this.recalculateEnemyPath(enemy);\n      return;\n    }\n\n    const distance = Phaser.Math.Distance.Between(enemy.body.x, enemy.body.y, target.x, target.y);\n    if (distance <= 0.001) {\n      enemy.body.setPosition(target.x, target.y);\n      enemy.pathIndex += 1;\n      if (this.pendingEnemyReroutes.has(enemy)) {\n        this.pendingEnemyReroutes.delete(enemy);\n        this.recalculateEnemyPath(enemy);\n      }\n      return;\n    }\n\n    const step = Math.min(distance, speed * (delta / 1000));\n    const nextX = enemy.body.x + ((target.x - enemy.body.x) / distance) * step;\n    const nextY = enemy.body.y + ((target.y - enemy.body.y) / distance) * step;\n    const halfPlant = PLANT_FRAME_SIZE / 2 - 1;\n    const movementBlocked = isEnemyMovementBlocked(\n      enemy.body.x,\n      enemy.body.y,\n      nextX,\n      nextY,\n      this.towers,\n      halfPlant,\n    );\n\n    if (movementBlocked) {\n      if (!this.rerouteEnemyFromSafeWaypoint(enemy)) {\n        this.pendingEnemyReroutes.add(enemy);\n      }\n      return;\n    }\n\n    enemy.body.setPosition(nextX, nextY);\n    if (step >= distance - 0.001) {\n      enemy.body.setPosition(target.x, target.y);\n      enemy.pathIndex += 1;\n      if (this.pendingEnemyReroutes.has(enemy)) {\n        this.pendingEnemyReroutes.delete(enemy);\n        this.recalculateEnemyPath(enemy);\n      }\n    }\n  }`;

export const FOLLOW_PATH_REPLACEMENT = `${SAFE_REROUTE_METHOD}\n\n${FOLLOW_PATH_METHOD}`;

export const RECALCULATE_ALL_ANCHOR = `  private recalculateEnemyPaths(): void {\n    const version = ++this.pathRecalculationVersion;\n    const activeEnemies = [...this.enemies];\n    const enemiesPerFrame = 6;\n    activeEnemies.forEach((enemy, index) => {\n      const delay = 1 + Math.floor(index / enemiesPerFrame) * 16;\n      const recalculate = (): void => {\n        if (version !== this.pathRecalculationVersion || !enemy.body.active || !this.enemies.includes(enemy)) return;\n        this.recalculateEnemyPath(enemy);\n      };\n      this.time.delayedCall(delay, recalculate);\n    });\n  }`;

export const RECALCULATE_ALL_REPLACEMENT = `  private recalculateEnemyPaths(): void {\n    this.pathRecalculationVersion += 1;\n    this.enemies.forEach((enemy) => {\n      if (enemy.body.active) this.pendingEnemyReroutes.add(enemy);\n    });\n  }`;
