export const IMPORT_ANCHOR = `import Phaser from "phaser";`;
export const IMPORT_REPLACEMENT = `import Phaser from "phaser";\nimport { isEnemyMovementBlocked } from "./game/enemyCollision";`;

export const FIELD_ANCHOR = "  private pathRecalculationVersion = 0;";
export const FIELD_REPLACEMENT = `  private pathRecalculationVersion = 0;\n  private pendingEnemyReroutes = new WeakSet<Enemy>();`;

export const FOLLOW_PATH_ANCHOR = `  private followPath(enemy: Enemy, delta: number, speed: number): void {\n    const target = enemy.path[enemy.pathIndex];\n    if (!target) {\n      this.recalculateEnemyPath(enemy);\n      return;\n    }\n\n    const distance = Phaser.Math.Distance.Between(enemy.body.x, enemy.body.y, target.x, target.y);\n    const step = speed * (delta / 1000);\n    if (distance <= step) {\n      enemy.body.setPosition(target.x, target.y);\n      enemy.pathIndex += 1;\n      return;\n    }\n    enemy.body.x += ((target.x - enemy.body.x) / distance) * step;\n    enemy.body.y += ((target.y - enemy.body.y) / distance) * step;\n  }`;

/** Reroute selection only. Movement/collision stays in FOLLOW_PATH_METHOD. */
export const SAFE_REROUTE_METHOD = `  private rerouteEnemyFromSafeWaypoint(enemy: Enemy): boolean {\n    const halfPlant = PLANT_FRAME_SIZE / 2 - 1;\n    const rightExit = {\n      id: "right" as ExitId,\n      col: TOP_EXIT_COL,\n      row: TOP_EXIT_ROW,\n      x: this.gridToWorldX(TOP_EXIT_COL, TOP_EXIT_ROW),\n      y: this.gridToWorldY(TOP_EXIT_ROW),\n    };\n    const bottomExit = {\n      id: "bottom" as ExitId,\n      col: BOTTOM_EXIT_COL,\n      row: BOTTOM_EXIT_ROW,\n      x: this.gridToWorldX(BOTTOM_EXIT_COL, BOTTOM_EXIT_ROW),\n      y: this.gridToWorldY(BOTTOM_EXIT_ROW),\n    };\n    const exits = enemy.exitId === "right" ? [rightExit, bottomExit] : [bottomExit, rightExit];\n\n    for (let safeIndex = Math.min(enemy.pathIndex - 1, enemy.path.length - 1); safeIndex >= 0; safeIndex -= 1) {\n      const waypoint = enemy.path[safeIndex];\n      const row = Phaser.Math.Clamp(Math.round((waypoint.y - GRID_Y) / CELL), 0, GRID_ROWS - 1);\n      const col = Phaser.Math.Clamp(Math.round((waypoint.x - GRID_X) / CELL), 0, GRID_COLS - 1);\n      const gridX = this.gridToWorldX(col, row);\n      const gridY = this.gridToWorldY(row);\n      if (Phaser.Math.Distance.Squared(waypoint.x, waypoint.y, gridX, gridY) > 4) continue;\n\n      const waypointBlocked = this.towers.some((tower) =>\n        Math.abs(gridX - tower.body.x) < halfPlant\n        && Math.abs(gridY - tower.body.y) < halfPlant,\n      );\n      if (waypointBlocked) continue;\n\n      for (const exit of exits) {\n        const route = this.calculatePath({ col, row }, { col: exit.col, row: exit.row });\n        if (!route) continue;\n\n        enemy.body.setPosition(gridX, gridY);\n        enemy.exitId = exit.id;\n        enemy.exitCol = exit.col;\n        enemy.exitRow = exit.row;\n        enemy.exitX = exit.x;\n        enemy.exitY = exit.y;\n        enemy.path = [\n          new Phaser.Math.Vector2(gridX, gridY),\n          ...route,\n          new Phaser.Math.Vector2(exit.x, exit.y),\n        ];\n        enemy.pathIndex = 1;\n        this.pendingEnemyReroutes.delete(enemy);\n        return true;\n      }\n    }\n\n    return false;\n  }`;

/** Movement plus the anti-tunnelling guard. */
export const FOLLOW_PATH_METHOD = `  private followPath(enemy: Enemy, delta: number, speed: number): void {\n    const target = enemy.path[enemy.pathIndex];\n    if (!target) {\n      this.pendingEnemyReroutes.delete(enemy);\n      this.recalculateEnemyPath(enemy);\n      return;\n    }\n\n    const distance = Phaser.Math.Distance.Between(enemy.body.x, enemy.body.y, target.x, target.y);\n    if (distance <= 0.001) {\n      enemy.body.setPosition(target.x, target.y);\n      enemy.pathIndex += 1;\n      if (this.pendingEnemyReroutes.has(enemy)) {\n        this.pendingEnemyReroutes.delete(enemy);\n        this.recalculateEnemyPath(enemy);\n      }\n      return;\n    }\n\n    const step = Math.min(distance, speed * (delta / 1000));\n    const nextX = enemy.body.x + ((target.x - enemy.body.x) / distance) * step;\n    const nextY = enemy.body.y + ((target.y - enemy.body.y) / distance) * step;\n    const halfPlant = PLANT_FRAME_SIZE / 2 - 1;\n    const movementBlocked = isEnemyMovementBlocked(\n      enemy.body.x,\n      enemy.body.y,\n      nextX,\n      nextY,\n      this.towers,\n      halfPlant,\n    );\n\n    if (movementBlocked) {\n      if (!this.rerouteEnemyFromSafeWaypoint(enemy)) {\n        this.pendingEnemyReroutes.add(enemy);\n      }\n      return;\n    }\n\n    enemy.body.setPosition(nextX, nextY);\n    if (step >= distance - 0.001) {\n      enemy.body.setPosition(target.x, target.y);\n      enemy.pathIndex += 1;\n      if (this.pendingEnemyReroutes.has(enemy)) {\n        this.pendingEnemyReroutes.delete(enemy);\n        this.recalculateEnemyPath(enemy);\n      }\n    }\n  }`;

export const FOLLOW_PATH_REPLACEMENT = `${SAFE_REROUTE_METHOD}\n\n${FOLLOW_PATH_METHOD}`;

export const RECALCULATE_ALL_ANCHOR = `  private recalculateEnemyPaths(): void {\n    const version = ++this.pathRecalculationVersion;\n    const activeEnemies = [...this.enemies];\n    const enemiesPerFrame = 6;\n    activeEnemies.forEach((enemy, index) => {\n      const delay = 1 + Math.floor(index / enemiesPerFrame) * 16;\n      const recalculate = (): void => {\n        if (version !== this.pathRecalculationVersion || !enemy.body.active || !this.enemies.includes(enemy)) return;\n        this.recalculateEnemyPath(enemy);\n      };\n      this.time.delayedCall(delay, recalculate);\n    });\n  }`;

export const RECALCULATE_ALL_REPLACEMENT = `  private recalculateEnemyPaths(): void {\n    this.pathRecalculationVersion += 1;\n    this.enemies.forEach((enemy) => {\n      if (enemy.body.active) this.pendingEnemyReroutes.add(enemy);\n    });\n  }`;
